# Generated by Django 5.2.16 on 2026-07-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=120)),
                ('xp', models.IntegerField(default=150)),
                ('avg_wpm', models.IntegerField(default=65)),
                ('avg_accuracy', models.IntegerField(default=97)),
                ('purchased_items', models.JSONField(blank=True, default=list)),
                ('active_sound', models.CharField(default='mechanical', max_length=50)),
                ('active_theme', models.CharField(default='cyberpunk', max_length=50)),
                ('key_metrics', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=100)),
                ('wpm', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('score', models.IntegerField()),
                ('coins_earned', models.IntegerField()),
                ('xp_earned', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
